# Generated by Django 3.1.11 on 2021-05-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_auto_20210522_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='timeZone',
        ),
    ]
